config/routes.rb
Rails.application.routes.draw do
  #get '/' => "pages#home" <=>
  root to: "pages#home"
    resources :restaurants do
      resources :reviews, only:[:create]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  #Validation
  validates :category, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"], allow_blank: false }
  validates :name, uniqueness: true, presence: true, allow_blank: false
  validates :address, presence: {message: "Il manque une adresse"}
end

app/models/review.rb
class Review < ApplicationRecord
  validates :restaurant_id, presence: true
  validates :content, presence: true
  belongs_to :restaurant
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @restaurants = Restaurant.all
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.all
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
     @review = Review.new
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit


  # POST /restaurants
  # POST /restaurants.json
  def create
     @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to @restaurant, notice: 'Restaurant was successfully created.'
    else
      render :new
    end
  end


  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
       def restaurant_params
      params.require(:restaurant).permit(:name, :address, :category, :phone_number)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant
  def create

  end
  def new
  end

    private
    def set_restaurant
      @restaurant = Restaurant.find(params[:restaurant_id])
      def review_params
        params.require(:review).permit(:content, :rating)
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <!-- app/views/layouts/application.html.erb -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  </head>

  <body>

  <%= render "shared/navbar" %>

    <%= yield %>

  <%= render "shared/footer" %>
   <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1 class= text-center >Welcome to Yelp</h1>

<div class="container">
  <div class="row">
  <% @restaurants.each do |restaurant| %>
    <div class="col-xs-12 col-sm-4">
      <%= render "restaurants/card", restaurant: restaurant %>
    </div>
  <% end %>

  </div>
  <div class="row">
  <%= link_to "allrestaurants", restaurants_path, class: "beautiful-link" %>

  </div>

</div>

app/views/restaurants/_card.html.erb
<div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://media-cdn.tripadvisor.com/media/photo-s/0b/4b/32/fb/restaurant-le-cinq.jpg');">
 <span class="card-shadow"></span>
  <span class="card-category"></span>
  <span class="card-description">french</span>
    <h2><%= restaurant.name%></h2>
    <p><%= restaurant.address%></p>
    <p>
    <% restaurant.stars do %>
    <i class="fa fa-stars"></i>
    <% end %>
    </p>
    <span class="card-user">
    <img src = 'http://placehold.it/50x50' class="avatar avatar-bordered"/>
    </span>
    <a href="#" class= "card-link"></a>
    <%=link_to "", restaurant_path(restaurant), class: "card-link"%>
  </div>

app/views/restaurants/_form.html.erb
<div class= "container">
  <div class="row">
  <div class= "col-xs-12 col-sm-6 col-sm-offset-3">
  <%= simple_form_for(@restaurant) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :category %>
    <%= f.input :phone_number %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<h1 class"text-center>The restaurants</h1>


<div class="container">
  <div class="row">
  <% @restaurants.each do |restaurant| %>
    <div class="col-xs-12 col-sm-4">
      <%= render "card", restaurant: restaurant %>
    </div>
  <% end %>

  </div>
</div>

app/views/restaurants/new.html.erb
<h1 class= "text-center">New Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<div class="text-center">
 <h2><%= @restaurant.name%></h2>
    <p><%= @restaurant.address%></p>
    <p>
    <% @restaurant.stars do %>
    <i class="fa fa-stars"></i>
    <% end %>
    </p>
    <p>
    <%= @restaurant.category%>
    </p>
    <p>
    <%= @restaurant.phone_number%>
    </p>

    <ul>
      <%@restaurant.reviews.each do |review| %>
      <%end%>
      <li>
      <%= review.content%>
       <% review.rating.times do %>
      <i class="fa fa-stars"></i>
      </li>
      <%end%>
    </ul>
  </div>


<%= simple_form_for([@restaurant, @review]) do |f| %>
  <%= f.input :content, input_html: {class:"my_input_class", id:'js-input'}, label_html:{class:"my_label_class"}, wrapper_html:{class:"my_wrapper_class"} %>
  <%= f.input :rating %>
  <%= f.submit %>
<% end %>






<%= link_to 'Edit', edit_restaurant_path(@restaurant) %> |
<%= link_to 'Back', restaurants_path %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
 <!-- Logo -->
 <%= link_to root_path, class: "navbar-wagon-brand" do %>
   <%= image_tag "logo.png" %>
 <% end %>

 <!-- Right Navigation -->
 <div class="navbar-wagon-right hidden-xs hidden-sm">

   <!-- Search form -->
   <form action="" class="navbar-wagon-search">
     <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
     <button type="submit" class="navbar-wagon-search-btn">
       <i class="fa fa-search"></i>
     </button>
   </form>

   <!-- Notification -->
   <%= link_to "#", class: "navbar-wagon-item navbar-wagon-link" do %>
     <div class="badge-container">
       <i class="fa fa-envelope-o"></i>
       <div class="badge badge-blue">3</div>
     </div>
   <% end %>

   <!-- Profile picture and dropdown -->
   <div class="navbar-wagon-item">
     <div class="dropdown">
       <%= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
       <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
         <li>
           <%= link_to "#" do %>
             <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
           <% end %>
         </li>
         <li>
           <%= link_to "#" do %>
             <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
           <% end %>
         </li>
       </ul>
     </div>
   </div>

   <!-- Button (call-to-action) -->
   <%= link_to t(".top_call_to_action", default: "Post stuff"), "#", class: "navbar-wagon-item navbar-wagon-button btn" %>
 </div>

 <!-- Dropdown list appearing on mobile only -->
 <div class="navbar-wagon-item hidden-md hidden-lg">
   <div class="dropdown">
     <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
     <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
       <li><a href="#">Some mobile link</a></li>
       <li><a href="#">Other one</a></li>
       <li><a href="#">Other one</a></li>
     </ul>
   </div>
 </div>
</div>